[package]
name = "cazic"
version = "0.0.1"
description = "Another music player written in Rust."
authors = ["Jaydon 'XandrCopyrighted' Nelson <xxandrr@proton.me>"]
license = "MIT"
repository = "https://github.com/XandrCopyrighted/Cazic"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5.4", features = ["shell-open"] }
color-thief = "0.2.2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true

[features]
custom-protocol = [ "tauri/custom-protocol" ]
