[package]
name = "cazic"
version = "0.0.2"
description = "Another music player written in Rust."
authors = ["Jaydon 'XandrCopyrighted' Nelson <xxandrr@proton.me>", "WilliamAnimate"]
license = "MIT"
repository = "https://github.com/XandrCopyrighted/Cazic"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
color-thief = "0.2.2"

[dependencies.tauri]
version = "1.5"
features = ["shell-open", "shell-open-api", "wry", "tauri-runtime-wry", "open"]
default-features = false

[build-dependencies.tauri-build]
version = "1.5"
features = []

[features]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true
